### ISSUE TITLE
Error após configuração

### ISSUE THREAD

**Issue by DaniJCV** [One-Shift/BO3-BOzon#3]
Após login com sucesso sou encaminhado para uma página inexistente (/bo3/backoffice/0/en/login/)~

O que poderei fazer?

**Comment by c42759** [comment]
@DaniJCV Esse situação devesse à falta de base de dados, pois a mesma ainda não foi disponibilizada por nós.
O BO3 ainda se encontra a receber alguns TWEAKs, e assim que finalizados será disponibilizada a base de dados junto com.

**Comment by DaniJCV** [comment]
Agradeço a resposta :)  Ficarei a aguardar!

**Comment by c42759** [comment]
@DaniJCV já se encontra disponivel um ficheiro de ajuda à instalação do BO3. Ao descarregares o projeto, o mesmo encontra-se através do endereço /path/to/bo3/install/

Alguma dúvida estamos aqui, ;)
